# Generated by Django 3.1.1 on 2020-09-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_info_management.category')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('ean', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=1024)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('categories', models.ManyToManyField(blank=True, null=True, related_name='articles', to='product_info_management.Category')),
            ],
        ),
    ]
