# Generated by Django 3.1.1 on 2020-09-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_info_management', '0002_auto_20200914_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ean',
            field=models.CharField(max_length=128, unique=True, verbose_name='EAN'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Defaults to 0'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sku',
            field=models.CharField(max_length=128, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product_info_management.category'),
        ),
    ]
