# Generated by Django 3.1.1 on 2020-09-15 12:36

import django.core.validators
from django.db import migrations, models
import product_info_management.enums
import product_info_management.validators
import re


class Migration(migrations.Migration):

    dependencies = [
        ('product_info_management', '0003_auto_20200914_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='currency',
            field=models.CharField(choices=[(product_info_management.enums.Currencies['Euro'], 'Euro'), (product_info_management.enums.Currencies['Dollar'], 'Dollar')], default='Dollar', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='ean',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message='EAN must be numerical. Can be "-" separated'), product_info_management.validators.EANValidator()], verbose_name='EAN'),
        ),
    ]
